# materials_library.py

tex_mat = {
    "SM_DragonHead_Trophy": {0: "DragonHead_Trophy_Colorize_MIC"},
    "SM_Fireplace_Base": {0: "MI_Fireplace_A"},
    "SM_Fireplace_Stack": {},
    "SM_Frontier_DoorCeilingXL": {0: "MI_Frontier_DoorCeilingXL_A", 1: "MI_Frontier_DoorCeilingXL_B"},
    "SM_Frontier_Pillar": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_Frontier_RoofSquare": {0: "MI_Frontier_RoofSquare"},
    "SM_Frontier_WallCorner_L": {0: "MI_Frontier_WallCorner"},
    "SM_Frontier_WallCorner_R": {0: "MI_Frontier_WallCorner"},
    "SM_Frontier_WallSquare":{0: "MI_Frontier_WallSquare"},
    "SM_GA_Deco_Statue_A": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_GA_Pillar_A1": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_GA_Pillar_A2": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_IceWyvern_Trophy": {0: "WyvernIce_colorized_MIC_RagWyvBoss", 1: "WyvernIceWings_colorized_MIC_RagWyvBoss", 2: "MI_WyvernIce_Eye_Refractive_RagWyvBoss"},
    "SM_KaijuDesert_Trophy": {0: "DesertKaiju_Eye_Refractive_Trophy", 1: "DesertKaiju_Wing_Trophy_MIC", 2: "DesertKaiju_Head_Trophy_MIC"},
    "SM_KaijuForest_Trophy": {0: "ForestKaiju_Body_Trophy_MIC"},
    "SM_KaijuIce_Trophy": {0: "IceKaiju_Eye_Refractive_Trophy", 1: "IceKaiju_head_Trophy_MIC", 2: "IceKaiju_body_Trophy_MIC", 3: "IceKaiju_Back_Trophy_MIC"},
    "SM_ManticoreTrophy": {0: "ManticoreBody_Colorize_MIC", 1: "MI_Manticore_Eye_Refractive", 2: "Manticore_Fur_Colorize_MIC"},
    "SM_SE_Ruins_Colosseum_FloorGrate_Wall": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_CornerPillar_A": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_CornerPillar_B": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_DecoBlock_A": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_DecoBlock_B": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_DecoBlock_C": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_DecoBlock_Corner": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_DoorWay_A": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_DoorWay_B": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Floor_A": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Floor_B": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Stairs_A": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_A": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_A_dmg": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_B": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_B_dmg": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_C": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_C_dmg": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_D": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_Pillar_A": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_Pillar_A_dmg": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_Pillar_B": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_Pillar_B_dmg": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_Window_A": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_Window_B": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_Window_B_dmg": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_Window_C": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SE_Ruins_Wall_Window_C_dmg": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_SpiralStairsS": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_Steampunk_Pillar_B": {0: "MIC_Badlands_Rocks_Ruins"},
    "SM_TrophyHeadBase": {0: "BaseTrophyHeads_MIC_Colorize"},
    "SM_SteampunkTable": {0: ""},
    "SM_KWoodTableV2": {0: ""},
    "SM_BeerBarrel": {0: ""},
    "SM_BarrelStorage": {0: ""},
    "SM_SaloonChair": {0: ""},
    "SM_KWoodChairV2": {0: ""},
    "SM_HumanBoneSet2Pile_5": {0: ""},
    "SM_Skeleton_Piece_01": {0: ""},
    "SM_Skeleton_Piece_02": {0: ""},
    "SM_Skeleton_Piece_06": {0: ""},
    "SM_Skeleton_Piece_09": {0: ""},
    "SM_Skeleton_Piece_10": {0: ""},
    "SM_Skeleton_Piece_11": {0: ""},
    "SM_Skeleton_Piece_15": {0: ""},
    "SM_Skeleton_Piece_16": {0: ""},
    "SM_Skeleton_Set_12": {0: ""},
    "SM_Skeleton_Set_18": {0: ""},
    "SM_Skeleton_Set_30": {0: ""},
    "SM_DecorBox_Medium": {0: ""},
    "SM_Cleaver": {0: ""},
    "Arrow01_SM": {0: ""},
    "SM_ScorchedGut": {0: ""},
    "SM_SwordForged": {0: ""},
    "SM_RR_Chandelier_1": {0: ""},
    "SM_Geo_root_stonePick": {0: ""},
    "SM_RR_TavernMug": {0: ""},
    "SM_RR_Bottle1": {0: ""},
    "SM_RR_Bottle2": {0: ""},
    "SM_RR_Bottle3": {0: ""},
    "SM_RR_Bottle_Rum_01": {0: ""},
    "SM_RR_Bottle_Rum_02": {0: ""},
    "SM_RR_Bottle_Rum_03": {0: ""},
    "SM_RR_Bottle_Rum_04": {0: ""},
    "SM_RR_BottleRack": {0: ""},
    "SM_RR_VikingShield2": {0: ""},
    "SM_RR_VikingShield3": {0: ""},
    "SM_RR_VikingShield4": {0: ""},
    "SM_RR_VikingShield5": {0: ""},
    "SM_RR_VikingShield6": {0: ""},
    "SM_RR_VikingShield7": {0: ""},
    "SM_RR_VikingShield8": {0: ""},
    "SM_RR_Picture_Frame1": {0: ""},
    "SM_RR_Picture_Frame2": {0: "RR_RP_MM_Structure_Wood1_Inst_0", 1: "15_Mat"},
    "SM_King_Sword_1": {0: ""},
    "SM_Shield_1": {0: ""},
    "SM_Shield_2": {0: ""},
    "SM_Shield_3": {0: ""},
    "SM_Shield_4": {0: ""},
    "SM_Shield_5": {0: ""},
    "SM_RR_Goblet": {0: ""},
    "SM_RR_Pitcher": {0: ""},
    "SM_Web2": {0: ""},
    "SM_Web3": {0: ""},
    "SM_Axe_1": {0: ""},
    "SM_Axe_2": {0: ""},
    "SM_Axe_3": {0: ""},
    "SM_Axe_4": {0: ""},
    "SM_Axe_5": {0: ""},
    "Sphere_Bushe_SM": {0: ""},
    "SM_vehCar_vehicle02_No_Wheel": {0: ""},
    "SM_Wheel_Front_L_vehCar_vehicle02": {0: ""},
    "SM_Skeleton_Set_24": {0: ""},
    "SM_PAA_ChipStack_100BB": {0: ""},
    "SM_PAA_ChipStack_150BB": {0: ""},
    "SM_PAA_ChipStack_200BB": {0: ""},
    "SM_PAA_ChipStack_400BB": {0: ""},
    "SM_PAA_ChipStack_600BB": {0: ""},
    "SM_PAA_TableWoodSH": {0: ""},
    "SM_SE_Ruins_Colosseum_Base_A": {0: ""},
    "SM_Gothic_HT_Lrg_Platform_A": {0: ""},
    'SM_RockDrakeEgg': {0: ""},
    'Heli_Egg': {0: ""},
    'SM_ShoulderDragonEgg': {0: ""},
    'SM_BogSpiderEgg': {0: ""},
    'SM_SnowDragonEgg': {0: ""},
    'DinoEgg': {0: ""},
    'SM_SpiderEgg_Custom': {0: ""},
    'CrystalWyvernEgg': {0: ""},
    'EggPiece01': {0: ""},
    'EggPiece02': {0: ""},
    'EggPiece03': {0: ""},
    'EggPiece04': {0: ""},
    'EggPiece05': {0: ""},
    'EggPiece06': {0: ""},
    'SM_SpiderEgg': {0: ""},
    'SM_SpiderEgg_noLarvae': {0: ""},
    'SM_SpiderEgg_2': {0: ""},
    'SM_SpiderEggs_Cluster': {0: ""},
    'EasterEgg': {0: ""},
    'SM_BrokenEgg': {0: ""},
    'DinoEgg_2': {0: ""},
    'SM_FishEgg': {0: ""},
    'SM_EggBroken_A': {0: ""},
    'SM_EggBroken_B': {0: ""},
    'SM_EggBroken_C': {0: ""},
    'SM_EggBroken_D': {0: ""},
    'SM_EggBroken_E': {0: ""},
    'SM_EggBroken_G': {0: ""},
    'SM_EggBroken_H': {0: ""},
    'SM_SmallEgg': {0: ""},
    'dragon_egg_1': {0: ""},
    'SM_RexCorpse01': {0: ""},
    'SM_RexCorpse02': {0: ""},
    'SM_Stego_Corpse01': {0: ""},
    'SM_FrozenCorpse01': {0: ""},
    'SM_FrozenCorpse02': {0: ""},
    'SM_FrozenCorpse03': {0: ""},
    'SM_CorpseBurlap_A': {0: ""},
    'SM_CorpseLeather': {0: ""},
    'SM_CorpseBurlap_B': {0: ""},
    'SP_CosmoPile2': {0: ""},
    'SP_CosmoPile3': {0: ""},
    'SM_Web_Impact_01': {0: ""},
    'SM_Web_Shell_01': {0: ""},
    'SM_Web_Shell_02': {0: ""},
    'Spiderweb': {0: ""},
    'Spiderweb02': {0: ""},
    'SM_SpiderFood1': {0: ""},
    'SM_SpiderFood2': {0: ""},
    'SM_SpiderFood3': {0: ""},
    'SM_SpiderFood4': {0: ""},
    'SM_SpiderFood5': {0: ""},
    'SM_Web1': {0: ""},
    'SM_Web4': {0: ""},
    'SM_WebRope': {0: ""},
    'SM_WebString1': {0: ""},
    'SM_WebString2': {0: ""},
}

path_mat = {
    "": "Default_value",
    "BaseTrophyHeads_MIC_Colorize": "/Game/PrimalEarth/Structures/TrophyHeads/BaseTrophyHeads_MIC_Colorize",
    "DesertKaiju_Eye_Refractive_Trophy": "/Game/Extinction/Structures/TrophyHeads/KaijuDesert/DesertKaiju_Eye_Refractive_Trophy",
    "DesertKaiju_Head_Trophy_MIC": "/Game/Extinction/Structures/TrophyHeads/KaijuDesert/DesertKaiju_Head_Trophy_MIC",
    "DesertKaiju_Wing_Trophy_MIC": "/Game/Extinction/Structures/TrophyHeads/KaijuDesert/DesertKaiju_Wing_Trophy_MIC",
    "DragonHead_Trophy_Colorize_MIC": "/Game/PrimalEarth/Structures/TrophyHeads/Dragon_TrophyHead/DragonHead_Trophy_Colorize_MIC",
    "ForestKaiju_Body_Trophy_MIC": "/Game/Extinction/Structures/TrophyHeads/KaijuForest/ForestKaiju_Body_Trophy_MIC",
    "IceKaiju_Back_Trophy_MIC": "/Game/Extinction/Structures/TrophyHeads/KaijuIce/IceKaiju_Back_Trophy_MIC",
    "IceKaiju_body_Trophy_MIC": "/Game/Extinction/Structures/TrophyHeads/KaijuIce/IceKaiju_body_Trophy_MIC",
    "IceKaiju_Eye_Refractive_Trophy": "/Game/Extinction/Structures/TrophyHeads/KaijuIce/IceKaiju_Eye_Refractive_Trophy",
    "IceKaiju_head_Trophy_MIC": "/Game/Extinction/Structures/TrophyHeads/KaijuIce/IceKaiju_head_Trophy_MIC",
    "Manticore_Fur_Colorize_MIC": "/Game/ScorchedEarth/Dinos/Manticore/Manticore_Fur_Colorize_MIC",
    "ManticoreBody_Colorize_MIC": "/Game/ScorchedEarth/Dinos/Manticore/ManticoreBody_Colorize_MIC",
    "MI_ASA_Ruins_Colosseum_FloorGrate": "/Game/ScorchedEarth/Environment/Shared/Ruins/Colosseum/MI_ASA_Ruins_Colosseum_FloorGrate",
    "MI_Frontier_DoorCeilingXL_A": "/Game/Packs/Frontier/Structures/Frontier/Textures/MI_Frontier_DoorCeilingXL_A",
    "MI_Frontier_DoorCeilingXL_B": "/Game/Packs/Frontier/Structures/Frontier/Textures/MI_Frontier_DoorCeilingXL_B",
    "MI_Frontier_RoofSquare": "/Game/Packs/Frontier/Structures/Frontier/Textures/MI_Frontier_RoofSquare",
    "MI_Frontier_WallCorner": "/Game/Packs/Frontier/Structures/Frontier/Textures/MI_Frontier_WallCorner",
    "MI_Frontier_WallSquare": "/Game/Packs/Frontier/Structures/Frontier/Textures/MI_Frontier_WallSquare",
    "MI_Manticore_Eye_Refractive": "/Game/ScorchedEarth/Dinos/Manticore/MI_Manticore_Eye_Refractive",
    "MI_WyvernIce_Eye_Refractive_RagWyvBoss": "/Game/ASA/Dinos/IceWyvern/Boss/MI_WyvernIce_Eye_Refractive_RagWyvBoss",
    "MIC_Badlands_Rocks_Ruins": "/Game/ScorchedEarth/Environment/Shared/Ruins/MIC_Badlands_Rocks_Ruins",
    "WyvernIce_colorized_MIC_RagWyvBoss": "/Game/ASA/Dinos/IceWyvern/Boss/WyvernIce_colorized_MIC_RagWyvBoss",
    "WyvernIceWings_colorized_MIC_RagWyvBoss": "/Game/ASA/Dinos/IceWyvern/Boss/WyvernIceWings_colorized_MIC_RagWyvBoss",
    "MI_Fireplace_A": "/Game/PrimalEarth/Structures/Fireplace/MI_Fireplace_A",
    "MI_Fireplace_B": "/Game/PrimalEarth/Structures/Fireplace/MI_Fireplace_B",
    "RR_RP_MM_Structure_Wood1_Inst_0": "/RR_Mod_MedievalRolePlayDeco/_MedievalRP_Mat_Inst/RR_RP_MM_Structure_Wood1_Inst_0",
    "1_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/1_Mat",
    "2_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/2_Mat",
    "3_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/3_Mat",
    "4_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/4_Mat",
    "5_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/5_Mat",
    "6_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/6_Mat",
    "7_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/7_Mat",
    "8_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/8_Mat",
    "9_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/9_Mat",
    "10_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/10_Mat",
    "11_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/11_Mat",
    "12_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/12_Mat",
    "13_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/13_Mat",
    "14_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/14_Mat",
    "15_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/15_Mat",
    "16_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/16_Mat",
    "17_Mat": "/RR_Mod_MedievalRolePlayDeco/Deco/Text_PictureWall/17_Mat",
}